enum RequestStatus {
  LOADING,
  SUCCESS,
  FAILURE, // EX: ACCOUNT ALREADY EXIST
  SERVER_FAILURE,
  INTERNAL_SERVER_ERROR,
  OFFLINE_FAILURE,
  UNKOWN_FAILURE,
  UNAUTHORIZED_FAILURE,

  EMPTY_SUCCESS,
}
