// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYI4WQJYSse1EqQJDxmZdSlxMHjmyvluY',
    appId: '1:22831482476:web:e68d14bb601770d3acba49',
    messagingSenderId: '22831482476',
    projectId: 'dentamatch-1ef31',
    authDomain: 'dentamatch-1ef31.firebaseapp.com',
    storageBucket: 'dentamatch-1ef31.appspot.com',
    measurementId: 'G-LR9DE9TVJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8aRhlHLYSy_y2448QoXWuoyZqBJXZvIg',
    appId: '1:22831482476:android:f00fdb25c78deabfacba49',
    messagingSenderId: '22831482476',
    projectId: 'dentamatch-1ef31',
    storageBucket: 'dentamatch-1ef31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW1qEb-HEOmZzZ4ncu954a7YI7PgNAI0M',
    appId: '1:22831482476:ios:31e9b5a85109c055acba49',
    messagingSenderId: '22831482476',
    projectId: 'dentamatch-1ef31',
    storageBucket: 'dentamatch-1ef31.appspot.com',
    iosBundleId: 'com.dentaMatch.dentamatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW1qEb-HEOmZzZ4ncu954a7YI7PgNAI0M',
    appId: '1:22831482476:ios:764dea32cc1c6e28acba49',
    messagingSenderId: '22831482476',
    projectId: 'dentamatch-1ef31',
    storageBucket: 'dentamatch-1ef31.appspot.com',
    iosBundleId: 'com.example.dentalmatching',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYI4WQJYSse1EqQJDxmZdSlxMHjmyvluY',
    appId: '1:22831482476:web:461ee660b89c9e5eacba49',
    messagingSenderId: '22831482476',
    projectId: 'dentamatch-1ef31',
    authDomain: 'dentamatch-1ef31.firebaseapp.com',
    storageBucket: 'dentamatch-1ef31.appspot.com',
    measurementId: 'G-B5QZXF9EY7',
  );

}